### ISSUE TITLE
Adding Pandas dependency

### ISSUE THREAD

**Issue by samfux84** [elzbth/jitterbug#1]
Dear Jitterbug developer,

as dependencies for jitterbug, you mention pysam, pybedtools and psutil. I have installed all of these modules and then tried to run jitterbug, which resulted in an error message about pandas not being installed.

```
[sfux@develop01 09032016]$ ./jitterbug.py -h
Traceback (most recent call last):
  File "./jitterbug.py", line 21, in <module>
    from Run_TE_ID_reseq import *
  File "/cluster/apps/gdc/jitterbug/09032016/Run_TE_ID_reseq.py", line 7, in <module>
    from BamReader import *
  File "/cluster/apps/gdc/jitterbug/09032016/BamReader.py", line 2, in <module>
    import pybedtools
  File "/cluster/apps/gdc/python/2.7.11/lib64/python2.7/site-packages/pybedtools-0.7.6-py2.7-linux-x86_64.egg/pybedtools/__init__.py", line 12, in <module>
    from . import contrib
  File "/cluster/apps/gdc/python/2.7.11/lib64/python2.7/site-packages/pybedtools-0.7.6-py2.7-linux-x86_64.egg/pybedtools/contrib/__init__.py", line 4, in <module>
    from . import long_range_interaction
  File "/cluster/apps/gdc/python/2.7.11/lib64/python2.7/site-packages/pybedtools-0.7.6-py2.7-linux-x86_64.egg/pybedtools/contrib/long_range_interaction.py", line 7, in <module>
    import pandas
ImportError: No module named pandas
```

Please add also the pandas package in the list of dependencies.

Thank you very much and best regards

Samuel Fux

**Comment by samfux84** [comment]
It also requires the Python package memory_profiler:

```
[sfux@develop01 09032016]$ ./jitterbug.py -h
Traceback (most recent call last):
  File "./jitterbug.py", line 21, in <module>
    from Run_TE_ID_reseq import *
  File "/cluster/apps/gdc/jitterbug/09032016/Run_TE_ID_reseq.py", line 18, in <module>
    from memory_profiler import profile
ImportError: No module named memory_profiler
```

**Comment by mbosio85** [comment]
Thanks for noticing. Now it has been included.
