### ISSUE TITLE
process_ND_TD.py error

### ISSUE THREAD

**Issue by kimsjune** [elzbth/jitterbug#15]
Hello,

I am facing the following error: 

Traceback (most recent call last):
  File "/home/skim823/projects/def-fdick/skim823/programs/jitterbug/tools/process_ND_TD.py", line 467, in <module>
    main(sys.argv[1:])
  File "/home/skim823/projects/def-fdick/skim823/programs/jitterbug/tools/process_ND_TD.py", line 85, in main
    for line in open(read_stats_file):
TypeError: coercing to Unicode: need string or buffer, NoneType found

I am running python 2.7.14.. I'd appreciate if anyone could help! Thanks

**Comment by niederhuth** [comment]
Hi,

I am also having the same issue and it seems that a cfg file is required, but I have no idea what this is supposed to look like or how to create one.

Thanks!

**Comment by Nisha-Hemandhar-Kumar** [comment]
Hi,
I am also having the same issue, however I don't understand what the cfg file is.
Thanks!

**Comment by sainadfensi** [comment]
Hi guys,

I guess the configure file (cfg) is the same file used in the step 1.2 for filtering. As the tumour gff is unfiltered, I think the step 2.2 is going to include the filtering of step 1.2. Haven't tested if I'm correct, good luck for myself.

Regards,
Jue
