### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by AnneJRomero** [elzbth/jitterbug#24]
I have installed jitterbug and I have the conda environment with the required dependencies:

psutil                    5.7.0            py27hdf8410d_1    conda-forge
pybedtools                0.8.1            py27h4bd9754_2    bioconda
pysam                     0.16.0.1         py27ha863e18_1    bioconda
python                    2.7.15          h5a48372_1011_cpython    conda-forge

but when testing it out I get the following error:
(TE27) [ar14g12@cyan51 jitterbug]$ jitterbug.py ../bam_files/D_L2_sort.bam ../TE_annotation/TE_anno.gff3
Traceback (most recent call last):
  File "./jitterbug.py", line 21, in <module>
    from Run_TE_ID_reseq import *
  File "/mainfs/scratch/ar14g12/PhD/tomato/TE/jitterbug/jitterbug/Run_TE_ID_reseq.py", line 6, in <module>
    import pysam
  File "/home/ar14g12/.local/lib/python2.7/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: /home/ar14g12/.local/lib/python2.7/site-packages/pysam/libchtslib.so: undefined symbol: PyUnicodeUCS2_DecodeUTF8

Googling the error it looks like there is a mismatch between the python installation and the package, one being encoded in unicodeUSC2 and the other in USC4.  
https://stackoverflow.com/questions/11878666/python-undefined-symbol-pyunicodeucs2-decodeutf8

Do you have a quick fix for this problem?

**Comment by hanshanmengqi** [comment]
Hi @AnneJRomero,

I think it's probably because of the version of dependencies.
In my case, I downloaded the dependencies as shown below:

matplotlib                     2.2.5                
matplotlib-base           2.2.5            
matplotlib-venn           0.11.5                  
memory-profiler           0.41    
numpy                     1.15.4
pandas                    0.24.2
pybedtools                0.7.10
pysam                     0.8.4
python                    2.7.15
setuptools                44.0.0

Hope it's helpful.

Han
